/*
** EPITECH PROJECT, 2019
** linux syscall
** File description:
** jooyoung.kim@epitech.eu
*/

#ifndef LINUX_SYSTEM_CALL_H_
#define LINUX_SYSTEM_CALL_H_

#include <stdbool.h>

typedef enum type_s
{
    INT,
    SSIZE_T,
    VOID_P,
    SIZE_T,
    CONST_VOID_P,
    CONST_CHAR_P,
    STRUCT_P,
    STRUCT_STAT_P,
    STRUCT_FD_P,
    NFDS_T,
    OFF_T,
    PVOID,
    CONST_KERNEL_SIGSET_T_P,
    KERNEL_SIGSET_T_P,
    UNSIGNED_LONG,
    VARGS,
    CONST_STRUCT_IOVEC_P,
    FD_SET_P,
    STRUCT_TIMEVAL_P,
    VOID,
    UNSIGNED_CHAR_P,
    KEY_T,
    STRUCT_SHMID_DS_P,
    CONST_STRUCT_TIMESPEC_P,
    STRUCT_TIMESPEC_P,
    STRUCT_ITIMERVAL_P,
    UNSIGNED_INT,
    CONST_STRUCT_ITIMERVAL_P,
    PID_T,
    OFF_T_P,
    CONST_STRUCT_SOCKADDR_P,
    SOCKLEN_T,
    STRUCT_SOCKADDR_P,
    SOCKLEN_T_P,
    CONST_STRUCT_MSGHDR_P, 
    STRUCT_MSGHDR_P,
    CHAR_P_CONST,
    INT_P,
    STRUCT_RUSAGE_P,
    STRUCT_UTSNAME_P,
    STRUCT_SEMBUF_P,
    LONG,
    STRUCT_MSQID_DS_P,
    STRUCT_LINUX_DIRENT_P,
    MODE_T,
    CHAR_P,
    UID_T,
    GID_T,
    STRUCT_TIMEZONE_P,
    STRUCT_RLIMIT_P,
    CLOCK_T,
    STRUCT_TMS_P,
    ENUM_____REQUEST,
    CONST_GID_T_P,
    UID_T_P,
    GID_T_P,
    CAP_USER_HEADER_T,
    CAP_USER_DATA_T,
    CONST_CAP_USER_DATA_T,
    CONST_STACK_T_P,
    STACK_T_P,
    CONST_STRUCT_UTIMBUF_P,
    DEV_T,
    STRUCT_STATFS_P,
    ID_T,
    CONST_STRUCT_SCHED_PARAM_P,
    STRUCT_SCHED_PARAM_P,
    STRUCT_TIMESPEC_P_,
    STRUCT____ARGS_P,
    STRUCT_TIMEX_P,
    CONST_STRUCT_RLIMIT_P,
    CONST_STRUCT_TIMEVAL_P,
    CONST_STRUCT_TIMEZONE_P,
    CADDR_T,
    STRUCT_KERNEL_SYM_P,
    SIZE_T_P,
    STRUCT_NFSCTL_ARG_P,
    UNION_NFSCTL_RES_P,
    OFF64_T,
    TIME_T,
    _T___T_P,
    CONST_CPU_SET_T_P,
    CPU_SET_T_P,
    STRUCT_USER_DESC_P,
    UNSIGNED,
    AIO_CONTEXT_T_P,
    AIO_CONTEXT_T,
    STRUCT_IO_EVENT_P,
    STRUCT_IOCB_P,
    U64,
    STRUCT_LINUX_DIRENT64_P,
    CLOCKID_T,
    STRUCT_SIGEVENT_P,
    TIMER_T_P,
    TIMER_T,
    CONST_STRUCT_ITIMERSPEC_P,
    STRUCT_ITIMERSPEC_P,
    STRUCT_EPOLL_EVENT_P,
    CONST_STRUCT_TIMEVAL,
    CONST_UNSIGNED_LONG_P,
    UNSIGNED_LONG_P,
    MQD_T,
    UNSIGNED_INT_P,
    CONST_STRUCT_SIGEVENT_P,
    STRUCT_MQ_ATTR_P,
    STRUCT_KEXEC_SEGMENT_P,
    IDTYPE_T,
    SIGINFO_T_P,
    KEY_SERIAL_T,
    UINT32_T,
    STRUCT_POLLFD_P,
    CONST_SIGSET_T_P,
    STRUCT_ROBUST_LIST_HEAD_P,
    LOFF_T_P,
    CONST_INT_P,
    CONST_STRUCT_TIMESPEC,
    STRUCT_PERF_EVENT_ATTR_P,
    STRUCT_MMSGHDR_P,
    UINT64_T,
    STRUCT_FILE_HANDLE_P,
    UNSIGNED_P,
    STRUCT__CACHE_P,
    STRUCT_SCHED_ATTR_P,
    UNION__ATTR_P,
    NONE
} type_t;

typedef struct linux_syscall_s
{
    int rax;
    char *name;
    bool ret;
    int args;
    type_t one;
    type_t two;
    type_t three;
    type_t four;
    type_t five;
    type_t six;
    type_t seven;
} linux_syscall_t;

static linux_syscall_t system_table [] =
{
    {0, "read", true, 3, SSIZE_T, INT, VOID_P, SIZE_T, 0, 0, 0},
    {1, "write", true, 3, SSIZE_T, INT, CONST_VOID_P, SIZE_T, 0, 0, 0},
    {2, "open", true, 2, INT, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {3, "close", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {4, "stat", true, 2, INT, CONST_CHAR_P, STRUCT_STAT_P, 0, 0, 0, 0},
    {5, "fstat", true, 2, INT, INT, STRUCT_STAT_P, 0, 0, 0, 0},
    {6, "lstat", true, 2, INT, CONST_CHAR_P, STRUCT_STAT_P, 0, 0, 0, 0},
    {7, "poll", true, 3, INT, STRUCT_FD_P, NFDS_T, INT, 0, 0, 0},
    {8, "lseek", true, 3, OFF_T, INT, OFF_T, INT, 0, 0, 0},
    {9, "mmap", true, 6, PVOID, VOID_P, SIZE_T, INT, INT, INT, OFF_T},
    {10, "mprotect", true, 3, INT, VOID_P, SIZE_T, INT, 0, 0, 0},
    {11, "munmap", true, 2, INT, VOID_P, SIZE_T, 0, 0, 0, 0},
    {12, "brk", true, 1, INT, VOID_P, 0, 0, 0, 0, 0},
    {13, "rt_sigaction", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {14, "rt_sigprocmask", true, 4,
    INT, INT, CONST_KERNEL_SIGSET_T_P, KERNEL_SIGSET_T_P, SIZE_T, 0, 0},
    {15, "rt_sigreturn", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {16, "ioctl", true, 3, INT, INT, UNSIGNED_LONG, VARGS, 0, 0, 0},
    {17, "pread64", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {18, "pwrite64", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {19, "readv", true, 3, SSIZE_T, INT, CONST_STRUCT_IOVEC_P, INT, 0, 0, 0},
    {20, "writev", true, 3, SSIZE_T, INT, CONST_STRUCT_IOVEC_P, INT, 0, 0, 0},
    {21, "access", true, 2, INT, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {22, "pipe", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {23, "select", true, 5,
    INT, INT, FD_SET_P, FD_SET_P, FD_SET_P, STRUCT_TIMEVAL_P, 0},
    {24, "sched_yield", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {25, "mremap", true, 0, PVOID, 0, 0, 0, 0, 0, 0},
    {26, "msync", true, 3, INT, VOID_P, SIZE_T, INT, 0, 0, 0},
    {27, "mincore", true, 3, INT, VOID_P, SIZE_T, UNSIGNED_CHAR_P, 0, 0, 0},
    {28, "madvise", true, 3, INT, VOID_P, SIZE_T, INT, 0, 0, 0},
    {29, "shmget", true, 3, INT, KEY_T, SIZE_T, INT, 0, 0, 0},
    {30, "shmat", true, 3, PVOID, INT, CONST_VOID_P, INT, 0, 0, 0},
    {31, "shmctl", true, 3, INT, INT, INT, STRUCT_SHMID_DS_P, 0, 0, 0},
    {32, "dup", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {33, "dup2", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {34, "pause", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {35, "nanosleep", true, 2,
    INT, CONST_STRUCT_TIMESPEC_P, STRUCT_TIMESPEC_P, 0, 0, 0, 0},
    {36, "getitimer", true, 2, INT, INT, STRUCT_ITIMERVAL_P, 0, 0, 0, 0},
    {37, "alarm", true, 1, UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0, 0, 0},
    {38, "setitimer", true, 3,
    INT, INT, CONST_STRUCT_ITIMERVAL_P, STRUCT_ITIMERVAL_P, 0, 0, 0},
    {39, "getpid", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {40, "sendfile", true, 4, SSIZE_T, INT, INT, OFF_T_P, SIZE_T, 0, 0},
    {41, "socket", true, 3, INT, INT, INT, INT, 0, 0, 0},
    {42, "connect", true, 3,
    INT, INT, CONST_STRUCT_SOCKADDR_P, SOCKLEN_T, 0, 0, 0},
    {43, "accept", true, 3, INT, INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
    {44, "sendto", true, 6, SSIZE_T,
    INT, CONST_VOID_P, SIZE_T, INT, CONST_STRUCT_SOCKADDR_P, SOCKLEN_T},
    {45, "recvfrom", true, 6,
    SSIZE_T, INT, VOID_P, SIZE_T, INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P},
    {46, "sendmsg", true, 3, SSIZE_T, INT,
    CONST_STRUCT_MSGHDR_P, INT, 0, 0, 0},
    {47, "recvmsg", true, 3, SSIZE_T, INT, STRUCT_MSGHDR_P, INT, 0, 0, 0},
    {48, "shutdown", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {49, "bind", true, 3, INT,
    INT, CONST_STRUCT_SOCKADDR_P, SOCKLEN_T, 0, 0, 0},
    {50, "listen", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {51, "getsockname", true, 3, INT,
    INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
    {52, "getpeername", true, 3, INT,
    INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, 0, 0, 0},
    {53, "socketpair", true, 4, INT, INT, INT, INT, INT, 0, 0},
    {54, "setsockopt", true, 5, INT,
    INT, INT, INT, CONST_VOID_P, SOCKLEN_T, 0},
    {55, "getsockopt", true, 5, INT, INT, INT, INT, VOID_P, SOCKLEN_T_P, 0},
    {56, "clone", true, 0, INT, 0, 0, 0, 0, 0, 0},
    {57, "fork", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {58, "vfork", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {59, "execve", true, 3, INT,
    CONST_CHAR_P, CHAR_P_CONST, CHAR_P_CONST, 0, 0, 0},
    {60, "exit", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {61, "wait4", true, 4, PID_T, PID_T, INT_P, INT, STRUCT_RUSAGE_P, 0, 0},
    {62, "kill", true, 2, INT, PID_T, INT, 0, 0, 0, 0},
    {63, "uname", true, 1, INT, STRUCT_UTSNAME_P, 0, 0, 0, 0, 0},
    {64, "semget", true, 3, INT, KEY_T, INT, INT, 0, 0, 0},
    {65, "semop", true, 3, INT, INT, STRUCT_SEMBUF_P, SIZE_T, 0, 0, 0},
    {66, "semctl", true, 4, INT, INT, INT, INT, VARGS, 0, 0},
    {67, "shmdt", true, 1, INT, CONST_VOID_P, 0, 0, 0, 0, 0},
    {68, "msgget", true, 2, INT, KEY_T, INT, 0, 0, 0, 0},
    {69, "msgsnd", true, 4, INT, INT, CONST_VOID_P, SIZE_T, INT, 0, 0},
    {70, "msgrcv", true, 5, SSIZE_T, INT, VOID_P, SIZE_T, LONG, INT, 0},
    {71, "msgctl", true, 3, INT, INT, INT, STRUCT_MSQID_DS_P, 0, 0, 0},
    {72, "fcntl", true, 0, INT, 0, 0, 0, 0, 0, 0},
    {73, "flock", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {74, "fsync", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {75, "fdatasync", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {76, "truncate", true, 2, INT, CONST_CHAR_P, OFF_T, 0, 0, 0, 0},
    {77, "ftruncate", true, 2, INT, INT, OFF_T, 0, 0, 0, 0},
    {78, "getdents", true, 3, INT,
    UNSIGNED_INT, STRUCT_LINUX_DIRENT_P, UNSIGNED_INT, 0, 0, 0},
    {79, "getcwd", true, 2, LONG, CHAR_P, UNSIGNED_LONG, 0, 0, 0, 0},
    {80, "chdir", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {81, "fchdir", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {82, "rename", true, 2, INT, CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {83, "mkdir", true, 2, INT, CONST_CHAR_P, MODE_T, 0, 0, 0, 0},
    {84, "rmdir", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {85, "creat", true, 2, INT, CONST_CHAR_P, MODE_T, 0, 0, 0, 0},
    {86, "link", true, 2, INT, CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {87, "unlink", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {88, "symlink", true, 2, INT, CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {89, "readlink", true, 3, SSIZE_T, CONST_CHAR_P, CHAR_P, SIZE_T, 0, 0, 0},
    {90, "chmod", true, 2, INT, CONST_CHAR_P, MODE_T, 0, 0, 0, 0},
    {91, "fchmod", true, 2, INT, INT, MODE_T, 0, 0, 0, 0},
    {92, "chown", true, 3, INT, CONST_CHAR_P, UID_T, GID_T, 0, 0, 0},
    {93, "fchown", true, 3, INT, INT, UID_T, GID_T, 0, 0, 0},
    {94, "lchown", true, 3, INT, CONST_CHAR_P, UID_T, GID_T, 0, 0, 0},
    {95, "umask", true, 1, MODE_T, MODE_T, 0, 0, 0, 0, 0},
    {96, "gettimeofday", true, 2, INT,
    STRUCT_TIMEVAL_P, STRUCT_TIMEZONE_P, 0, 0, 0, 0},
    {97, "getrlimit", true, 2, INT, INT, STRUCT_RLIMIT_P, 0, 0, 0, 0},
    {98, "getrusage", true, 2, INT, INT, STRUCT_RUSAGE_P, 0, 0, 0, 0},
    {99, "sysinfo", true, 1, INT, STRUCT_P, 0, 0, 0, 0, 0},
    {100, "times", true, 1, CLOCK_T, STRUCT_TMS_P, 0, 0, 0, 0, 0},
    {101, "ptrace", true, 4, LONG,
    ENUM_____REQUEST, PID_T, VOID_P, VOID_P, 0, 0},
    {102, "getuid", true, 1, UID_T, VOID, 0, 0, 0, 0, 0},
    {103, "syslog", true, 3, INT, INT, CHAR_P, INT, 0, 0, 0},
    {104, "getgid", true, 1, GID_T, VOID, 0, 0, 0, 0, 0},
    {105, "setuid", true, 1, INT, UID_T, 0, 0, 0, 0, 0},
    {106, "setgid", true, 1, INT, GID_T, 0, 0, 0, 0, 0},
    {107, "geteuid", true, 1, UID_T, VOID, 0, 0, 0, 0, 0},
    {108, "getegid", true, 1, GID_T, VOID, 0, 0, 0, 0, 0},
    {109, "setpgid", true, 2, INT, PID_T, PID_T, 0, 0, 0, 0},
    {110, "getppid", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {111, "getpgrp", true, 0, PID_T, 0, 0, 0, 0, 0, 0},
    {112, "setsid", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {113, "setreuid", true, 2, INT, UID_T, UID_T, 0, 0, 0, 0},
    {114, "setregid", true, 2, INT, GID_T, GID_T, 0, 0, 0, 0},
    {115, "getgroups", true, 2, INT, INT, GID_T, 0, 0, 0, 0},
    {116, "setgroups", true, 2, INT, SIZE_T, CONST_GID_T_P, 0, 0, 0, 0},
    {117, "setresuid", true, 3, INT, UID_T, UID_T, UID_T, 0, 0, 0},
    {118, "getresuid", true, 3, INT, UID_T_P, UID_T_P, UID_T_P, 0, 0, 0},
    {119, "setresgid", true, 3, INT, GID_T, GID_T, GID_T, 0, 0, 0},
    {120, "getresgid", true, 3, INT, GID_T_P, GID_T_P, GID_T_P, 0, 0, 0},
    {121, "getpgid", true, 1, PID_T, PID_T, 0, 0, 0, 0, 0},
    {122, "setfsuid", true, 1, INT, UID_T, 0, 0, 0, 0, 0},
    {123, "setfsgid", true, 1, INT, UID_T, 0, 0, 0, 0, 0},
    {124, "getsid", true, 1, PID_T, PID_T, 0, 0, 0, 0, 0},
    {125, "capget", true, 2, INT,
    CAP_USER_HEADER_T, CAP_USER_DATA_T, 0, 0, 0, 0},
    {126, "capset", true, 2, INT,
    CAP_USER_HEADER_T, CONST_CAP_USER_DATA_T, 0, 0, 0, 0},
    {127, "rt_sigpending", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {128, "rt_sigtimedwait", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {129, "rt_sigqueueinfo", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {130, "rt_sigsuspend", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {131, "sigaltstack", true, 2, INT, CONST_STACK_T_P, STACK_T_P, 0, 0, 0, 0},
    {132, "utime", true, 2, INT,
    CONST_CHAR_P, CONST_STRUCT_UTIMBUF_P, 0, 0, 0, 0},
    {133, "mknod", true, 3, INT, CONST_CHAR_P, MODE_T, DEV_T, 0, 0, 0},
    {134, "uselib", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {135, "personality", true, 1, INT, UNSIGNED_LONG, 0, 0, 0, 0, 0},
    {136, "ustat", true, 2, INT, DEV_T, STRUCT_P, 0, 0, 0, 0},
    {137, "statfs", true, 2, INT, CONST_CHAR_P, STRUCT_P, 0, 0, 0, 0},
    {138, "fstatfs", true, 2, INT, INT, STRUCT_STATFS_P, 0, 0, 0, 0},
    {139, "sysfs", true, 2, INT, INT, CONST_CHAR_P, 0, 0, 0, 0},
    {140, "getpriority", true, 2, INT, INT, ID_T, 0, 0, 0, 0},
    {141, "setpriority", true, 3, INT, INT, ID_T, INT, 0, 0, 0},
    {142, "sched_setparam", true, 2, INT,
    PID_T, CONST_STRUCT_SCHED_PARAM_P, 0, 0, 0, 0},
    {143, "sched_getparam", true, 2, INT,
    PID_T, STRUCT_SCHED_PARAM_P, 0, 0, 0, 0},
    {144, "sched_setscheduler", true, 3, INT,
    PID_T, INT, CONST_STRUCT_SCHED_PARAM_P, 0, 0, 0},
    {145, "sched_getscheduler", true, 1, INT, PID_T, 0, 0, 0, 0, 0},
    {146, "sched_get_priority_max", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {147, "sched_get_priority_min", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {148, "sched_rr_get_interval", true, 2, INT,
    PID_T, STRUCT_TIMESPEC_P_, 0, 0, 0, 0},
    {149, "mlock", true, 2, INT, CONST_VOID_P, SIZE_T, 0, 0, 0, 0},
    {150, "munlock", true, 2, INT, CONST_VOID_P, SIZE_T, 0, 0, 0, 0},
    {151, "mlockall", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {152, "munlockall", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {153, "vhangup", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {154, "modify_ldt", true, 3, INT, INT, VOID_P, UNSIGNED_LONG, 0, 0, 0},
    {155, "pivot_root", true, 2, INT, CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {156, "_sysctl", true, 1, INT, STRUCT____ARGS_P, 0, 0, 0, 0, 0},
    {157, "prctl", true, 5, INT,
    INT, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {158, "arch_prctl", true, 2, INT, INT, UNSIGNED_LONG, 0, 0, 0, 0},
    {159, "adjtimex", true, 1, INT, STRUCT_TIMEX_P, 0, 0, 0, 0, 0},
    {160, "setrlimit", true, 2, INT, INT, CONST_STRUCT_RLIMIT_P, 0, 0, 0, 0},
    {161, "chroot", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {162, "sync", true, 1, VOID, VOID, 0, 0, 0, 0, 0},
    {163, "acct", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {164, "settimeofday", true, 2, INT,
    CONST_STRUCT_TIMEVAL_P, CONST_STRUCT_TIMEZONE_P, 0, 0, 0, 0},
    {165, "mount", true, 5, INT,
    CONST_CHAR_P, CONST_CHAR_P, CONST_CHAR_P, UNSIGNED_LONG, CONST_VOID_P, 0},
    {166, "umount2", true, 2, INT, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {167, "swapon", true, 2, INT, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {168, "swapoff", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {169, "reboot", true, 4, INT, INT, INT, INT, VOID_P, 0, 0},
    {170, "sethostname", true, 2, INT, CONST_CHAR_P, SIZE_T, 0, 0, 0, 0},
    {171, "setdomainname", true, 2, INT, CONST_CHAR_P, SIZE_T, 0, 0, 0, 0},
    {172, "iopl", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {173, "ioperm", true, 3, INT, UNSIGNED_LONG, UNSIGNED_LONG, INT, 0, 0, 0},
    {174, "create_module", true, 2, CADDR_T, CONST_CHAR_P, SIZE_T, 0, 0, 0, 0},
    {175, "init_module", true, 3, INT,
    VOID_P, UNSIGNED_LONG, CONST_CHAR_P, 0, 0, 0},
    {176, "delete_module", true, 2, INT, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {177, "get_kernel_syms", true, 1, INT, STRUCT_KERNEL_SYM_P, 0, 0, 0, 0, 0},
    {178, "query_module", true, 5, INT,
    CONST_CHAR_P, INT, VOID_P, SIZE_T, SIZE_T_P, 0},
    {179, "quotactl", true, 4, INT, INT, CONST_CHAR_P, INT, CADDR_T, 0, 0},
    {180, "nfsservctl", true, 3, LONG,
    INT, STRUCT_NFSCTL_ARG_P, UNION_NFSCTL_RES_P, 0, 0, 0},
    {181, "getpmsg", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {182, "putpmsg", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {183, "afs_syscall", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {184, "tuxcall", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {185, "security", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {186, "gettid", true, 1, PID_T, VOID, 0, 0, 0, 0, 0},
    {187, "readahead", true, 3, SSIZE_T, INT, OFF64_T, SIZE_T, 0, 0, 0},
    {188, "setxattr", true, 5, INT,
    CONST_CHAR_P, CONST_CHAR_P, CONST_VOID_P, SIZE_T, INT, 0},
    {189, "lsetxattr", true, 5, INT,
    CONST_CHAR_P, CONST_CHAR_P, CONST_VOID_P, SIZE_T, INT, 0},
    {190, "fsetxattr", true, 5, INT,
    INT, CONST_CHAR_P, CONST_VOID_P, SIZE_T, INT, 0},
    {191, "getxattr", true, 4, SSIZE_T,
    CONST_CHAR_P, CONST_CHAR_P, VOID_P, SIZE_T, 0, 0},
    {192, "lgetxattr", true, 4, SSIZE_T,
    CONST_CHAR_P, CONST_CHAR_P, VOID_P, SIZE_T, 0, 0},
    {193, "fgetxattr", true, 4, SSIZE_T,
    INT, CONST_CHAR_P, VOID_P, SIZE_T, 0, 0},
    {194, "listxattr", true, 3, SSIZE_T,
    CONST_CHAR_P, CHAR_P, SIZE_T, 0, 0, 0},
    {195, "llistxattr", true, 3, SSIZE_T,
    CONST_CHAR_P, CHAR_P, SIZE_T, 0, 0, 0},
    {196, "flistxattr", true, 3, SSIZE_T, INT, CHAR_P, SIZE_T, 0, 0, 0},
    {197, "removexattr", true, 2, INT,
    CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {198, "lremovexattr", true, 2, INT,
    CONST_CHAR_P, CONST_CHAR_P, 0, 0, 0, 0},
    {199, "fremovexattr", true, 2, INT, INT, CONST_CHAR_P, 0, 0, 0, 0},
    {200, "tkill", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {201, "time", true, 1, TIME_T, _T___T_P, 0, 0, 0, 0, 0},
    {202, "futex", true, 0, INT, 0, 0, 0, 0, 0, 0},
    {203, "sched_setaffinity", true, 3, INT,
    PID_T, SIZE_T, CONST_CPU_SET_T_P, 0, 0, 0},
    {204, "sched_getaffinity", true, 3, INT,
    PID_T, SIZE_T, CPU_SET_T_P, 0, 0, 0},
    {205, "set_thread_area", true, 1, INT, STRUCT_USER_DESC_P, 0, 0, 0, 0, 0},
    {206, "io_setup", true, 2, INT, UNSIGNED, AIO_CONTEXT_T_P, 0, 0, 0, 0},
    {207, "io_destroy", true, 1, INT, AIO_CONTEXT_T, 0, 0, 0, 0, 0},
    {208, "io_getevents", true, 5, INT,
    AIO_CONTEXT_T, LONG, LONG, STRUCT_IO_EVENT_P, STRUCT_TIMESPEC_P, 0},
    {209, "io_submit", true, 3, INT,
    AIO_CONTEXT_T, LONG, STRUCT_IOCB_P, 0, 0, 0},
    {210, "io_cancel", true, 3, INT,
    AIO_CONTEXT_T, STRUCT_IOCB_P, STRUCT_IO_EVENT_P, 0, 0, 0},
    {211, "get_thread_area", true, 1, INT, STRUCT_USER_DESC_P, 0, 0, 0, 0, 0},
    {212, "lookup_dcookie", true, 3, INT, U64, CHAR_P, SIZE_T, 0, 0, 0},
    {213, "epoll_create", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {214, "epoll_ctl_old", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {215, "epoll_wait_old", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {216, "remap_file_pages", true, 5, INT,
    VOID_P, SIZE_T, INT, SIZE_T, INT, 0},
    {217, "getdents64", true, 3, INT,
    UNSIGNED_INT, STRUCT_LINUX_DIRENT64_P, UNSIGNED_INT, 0, 0, 0},
    {218, "set_tid_address", true, 1, LONG, INT_P, 0, 0, 0, 0, 0},
    {219, "restart_syscall", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {220, "semtimedop", true, 4, INT,
    INT, STRUCT_SEMBUF_P, SIZE_T, CONST_STRUCT_TIMESPEC_P, 0, 0},
    {221, "fadvise64", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {222, "timer_create", true, 3, INT,
    CLOCKID_T, STRUCT_SIGEVENT_P, TIMER_T_P, 0, 0, 0},
    {223, "timer_settime", true, 4, INT,
    TIMER_T, INT, CONST_STRUCT_ITIMERSPEC_P, STRUCT_ITIMERSPEC_P, 0, 0},
    {224, "timer_gettime", true, 2, INT,
    TIMER_T, STRUCT_ITIMERSPEC_P, 0, 0, 0, 0},
    {225, "timer_getoverrun", true, 1, INT, TIMER_T, 0, 0, 0, 0, 0},
    {226, "timer_delete", true, 1, INT, TIMER_T, 0, 0, 0, 0, 0},
    {227, "clock_settime", true, 2, INT,
    CLOCKID_T, CONST_STRUCT_TIMESPEC_P, 0, 0, 0, 0},
    {228, "clock_gettime", true, 2, INT,
    CLOCKID_T, STRUCT_TIMESPEC_P, 0, 0, 0, 0},
    {229, "clock_getres", true, 2, INT,
    CLOCKID_T, STRUCT_TIMESPEC_P, 0, 0, 0, 0},
    {230, "clock_nanosleep", true, 4, INT,
    CLOCKID_T, INT, CONST_STRUCT_TIMESPEC_P, STRUCT_TIMESPEC_P, 0, 0},
    {231, "exit_group", true, 1, VOID, INT, 0, 0, 0, 0, 0},
    {232, "epoll_wait", true, 4, INT,
    INT, STRUCT_EPOLL_EVENT_P, INT, INT, 0, 0},
    {233, "epoll_ctl", true, 4, INT,
    INT, INT, INT, STRUCT_EPOLL_EVENT_P, 0, 0},
    {234, "tgkill", true, 3, INT, INT, INT, INT, 0, 0, 0},
    {235, "utimes", true, 2, INT,
    CONST_CHAR_P, CONST_STRUCT_TIMEVAL, 0, 0, 0, 0},
    {236, "vserver", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {237, "mbind", true, 6, LONG, VOID_P, UNSIGNED_LONG,
    INT, CONST_UNSIGNED_LONG_P, UNSIGNED_LONG, UNSIGNED},
    {238, "set_mempolicy", true, 3, LONG,
    INT, CONST_UNSIGNED_LONG_P, UNSIGNED_LONG, 0, 0, 0},
    {239, "get_mempolicy", true, 5, INT,
    INT_P, UNSIGNED_LONG_P, UNSIGNED_LONG, VOID_P, UNSIGNED_LONG, 0},
    {240, "mq_open", true, 2, MQD_T, CONST_CHAR_P, INT, 0, 0, 0, 0},
    {241, "mq_unlink", true, 1, INT, CONST_CHAR_P, 0, 0, 0, 0, 0},
    {242, "mq_timedsend", true, 5, INT,
    MQD_T, CONST_CHAR_P, SIZE_T, UNSIGNED_INT, CONST_STRUCT_TIMESPEC_P, 0},
    {243, "mq_timedreceive", true, 5, SSIZE_T,
    MQD_T, CHAR_P, SIZE_T, UNSIGNED_INT_P, CONST_STRUCT_TIMESPEC_P, 0},
    {244, "mq_notify", true, 2, INT,
    MQD_T, CONST_STRUCT_SIGEVENT_P, 0, 0, 0, 0},
    {245, "mq_getsetattr", true, 3, INT,
    MQD_T, STRUCT_MQ_ATTR_P, STRUCT_MQ_ATTR_P, 0, 0, 0},
    {246, "kexec_load", true, 4, LONG, UNSIGNED_LONG, UNSIGNED_LONG,
    STRUCT_KEXEC_SEGMENT_P, UNSIGNED_LONG, 0, 0},
    {247, "waitid", true, 4, INT, IDTYPE_T, ID_T, SIGINFO_T_P, INT, 0, 0},
    {248, "add_key", true, 5, KEY_SERIAL_T,
    CONST_CHAR_P, CONST_CHAR_P, CONST_VOID_P, SIZE_T, KEY_SERIAL_T, 0},
    {249, "request_key", true, 4, KEY_SERIAL_T,
    CONST_CHAR_P, CONST_CHAR_P, CONST_CHAR_P, KEY_SERIAL_T, 0, 0},
    {250, "keyctl", true, 2, LONG, INT, VARGS, 0, 0, 0, 0},
    {251, "ioprio_set", true, 3, INT, INT, INT, INT, 0, 0, 0},
    {252, "ioprio_get", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {253, "inotify_init", true, 1, INT, VOID, 0, 0, 0, 0, 0},
    {254, "inotify_add_watch", true, 3, INT,
    INT, CONST_CHAR_P, UINT32_T, 0, 0, 0},
    {255, "inotify_rm_watch", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {256, "migrate_pages", true, 4, LONG,
    INT, UNSIGNED_LONG, CONST_UNSIGNED_LONG_P, CONST_UNSIGNED_LONG_P, 0, 0},
    {257, "openat", true, 3, INT, INT, CONST_CHAR_P, INT, 0, 0, 0},
    {258, "mkdirat", true, 3, INT, INT, CONST_CHAR_P, MODE_T, 0, 0, 0},
    {259, "mknodat", true, 4, INT, INT, CONST_CHAR_P, MODE_T, DEV_T, 0, 0},
    {260, "fchownat", true, 5, INT, INT, CONST_CHAR_P, UID_T, GID_T, INT, 0},
    {261, "futimesat", true, 3, INT,
    INT, CONST_CHAR_P, CONST_STRUCT_TIMEVAL, 0, 0, 0},
    {262, "newfstatat", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {263, "unlinkat", true, 3, INT, INT, CONST_CHAR_P, INT, 0, 0, 0},
    {264, "renameat", true, 4, INT, INT,
    CONST_CHAR_P, INT, CONST_CHAR_P, 0, 0},
    {265, "linkat", true, 5, INT, INT,
    CONST_CHAR_P, INT, CONST_CHAR_P, INT, 0},
    {266, "symlinkat", true, 3, INT, CONST_CHAR_P, INT, CONST_CHAR_P, 0, 0, 0},
    {267, "readlinkat", true, 4, SSIZE_T,
    INT, CONST_CHAR_P, CHAR_P, SIZE_T, 0, 0},
    {268, "fchmodat", true, 4, INT, INT, CONST_CHAR_P, MODE_T, INT, 0, 0},
    {269, "faccessat", true, 4, INT, INT, CONST_CHAR_P, INT, INT, 0, 0},
    {270, "pselect6", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {271, "ppoll", true, 4, INT,
    STRUCT_POLLFD_P, NFDS_T, CONST_STRUCT_TIMESPEC_P, CONST_SIGSET_T_P, 0, 0},
    {272, "unshare", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {273, "set_robust_list", true, 2, LONG,
    STRUCT_ROBUST_LIST_HEAD_P, SIZE_T, 0, 0, 0, 0},
    {274, "get_robust_list", true, 3, LONG,
    INT, STRUCT_ROBUST_LIST_HEAD_P, SIZE_T_P, 0, 0, 0},
    {275, "splice", true, 6, SSIZE_T,
    INT, LOFF_T_P, INT, LOFF_T_P, SIZE_T, UNSIGNED_INT},
    {276, "tee", true, 4, SSIZE_T, INT, INT, SIZE_T, UNSIGNED_INT, 0, 0},
    {277, "sync_file_range", true, 4, INT,
    INT, OFF64_T, OFF64_T, UNSIGNED_INT, 0, 0},
    {278, "vmsplice", true, 4, SSIZE_T,
    INT, CONST_STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_INT, 0, 0},
    {279, "move_pages", true, 6, LONG,
    INT, UNSIGNED_LONG, VOID_P, CONST_INT_P, INT_P, INT},
    {280, "utimensat", true, 4, INT,
    INT, CONST_CHAR_P, CONST_STRUCT_TIMESPEC, INT, 0, 0},
    {281, "epoll_pwait", true, 5, INT,
    INT, STRUCT_EPOLL_EVENT_P, INT, INT, CONST_SIGSET_T_P, 0},
    {282, "signalfd", true, 3, INT, INT, CONST_SIGSET_T_P, INT, 0, 0, 0},
    {283, "timerfd_create", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {284, "eventfd", true, 2, INT, UNSIGNED_INT, INT, 0, 0, 0, 0},
    {285, "fallocate", true, 4, INT, INT, INT, OFF_T, OFF_T, 0, 0},
    {286, "timerfd_settime", true, 4, INT,
    INT, INT, CONST_STRUCT_ITIMERSPEC_P, STRUCT_ITIMERSPEC_P, 0, 0},
    {287, "timerfd_gettime", true, 2, INT,
    INT, STRUCT_ITIMERSPEC_P, 0, 0, 0, 0},
    {288, "accept4", true, 4, INT,
    INT, STRUCT_SOCKADDR_P, SOCKLEN_T_P, INT, 0, 0},
    {289, "signalfd4", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {290, "eventfd2", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {291, "epoll_create1", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {292, "dup3", true, 3, INT, INT, INT, INT, 0, 0, 0},
    {293, "pipe2", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {294, "inotify_init1", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {295, "preadv", true, 4, SSIZE_T,
    INT, CONST_STRUCT_IOVEC_P, INT, OFF_T, 0, 0},
    {296, "pwritev", true, 4, SSIZE_T,
    INT, CONST_STRUCT_IOVEC_P, INT, OFF_T, 0, 0},
    {297, "rt_tgsigqueueinfo", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {298, "perf_event_open", true, 5, INT,
    STRUCT_PERF_EVENT_ATTR_P, PID_T, INT, INT, UNSIGNED_LONG, 0},
    {299, "recvmmsg", true, 5, INT,
    INT, STRUCT_MMSGHDR_P, UNSIGNED_INT, UNSIGNED_INT, STRUCT_TIMESPEC_P, 0},
    {300, "fanotify_init", true, 2, INT,
    UNSIGNED_INT, UNSIGNED_INT, 0, 0, 0, 0},
    {301, "fanotify_mark", true, 5, INT,
    INT, UNSIGNED_INT, UINT64_T, INT, CONST_CHAR_P, 0},
    {302, "prlimit64", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {303, "name_to_handle_at", true, 5, INT,
    INT, CONST_CHAR_P, STRUCT_FILE_HANDLE_P, INT_P, INT, 0},
    {304, "open_by_handle_at", true, 3, INT,
    INT, STRUCT_FILE_HANDLE_P, INT, 0, 0, 0},
    {305, "clock_adjtime", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {306, "syncfs", true, 1, INT, INT, 0, 0, 0, 0, 0},
    {307, "sendmmsg", true, 4, INT,
    INT, STRUCT_MMSGHDR_P, UNSIGNED_INT, UNSIGNED_INT, 0, 0},
    {308, "setns", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {309, "getcpu", true, 3, INT,
    UNSIGNED_P, UNSIGNED_P, STRUCT__CACHE_P, 0, 0, 0},
    {310, "process_vm_readv", true, 6, SSIZE_T, PID_T, CONST_STRUCT_IOVEC_P,
    UNSIGNED_LONG, CONST_STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG},
    {311, "process_vm_writev", true, 6, SSIZE_T, PID_T, CONST_STRUCT_IOVEC_P,
    UNSIGNED_LONG, CONST_STRUCT_IOVEC_P, UNSIGNED_LONG, UNSIGNED_LONG},
    {312, "kcmp", true, 5, INT,
    PID_T, PID_T, INT, UNSIGNED_LONG, UNSIGNED_LONG, 0},
    {313, "finit_module", true, 3, INT, INT, CONST_CHAR_P, INT, 0, 0, 0},
    {314, "sched_setattr", true, 3, INT,
    PID_T, STRUCT_SCHED_ATTR_P, UNSIGNED_INT, 0, 0, 0},
    {315, "sched_getattr", true, 4, INT,
    PID_T, STRUCT_SCHED_ATTR_P, UNSIGNED_INT, UNSIGNED_INT, 0, 0},
    {316, "renameat2", true, 5, INT,
    INT, CONST_CHAR_P, INT, CONST_CHAR_P, UNSIGNED_INT, 0},
    {317, "seccomp", true, 3, INT,
    UNSIGNED_INT, UNSIGNED_INT, VOID_P, 0, 0, 0},
    {318, "getrandom", true, 3, INT, VOID_P, SIZE_T, UNSIGNED_INT, 0, 0, 0},
    {319, "memfd_create", true, 2, INT,
    CONST_CHAR_P, UNSIGNED_INT, 0, 0, 0, 0},
    {320, "kexec_file_load", true, 5, LONG,
    INT, INT, UNSIGNED_LONG, CONST_CHAR_P, UNSIGNED_LONG, 0},
    {321, "bpf", true, 3, INT, INT, UNION__ATTR_P, UNSIGNED_INT, 0, 0, 0},
    {322, "execveat", true, 5, INT,
    INT, CONST_CHAR_P, CHAR_P_CONST, CHAR_P_CONST, INT, 0},
    {323, "userfaultfd", false, 6, 0, 0, 0, 0, 0, 0, 0},
    {324, "membarrier", true, 2, INT, INT, INT, 0, 0, 0, 0},
    {325, "mlock2", true, 3, INT, CONST_VOID_P, SIZE_T, INT, 0, 0, 0},
    {326, "copy_file_range", true, 6, SSIZE_T,
    INT, LOFF_T_P, INT, LOFF_T_P, SIZE_T, UNSIGNED_INT},
    {327, "preadv2", true, 5, SSIZE_T,
    INT, CONST_STRUCT_IOVEC_P, INT, OFF_T, INT, 0},
    {328, "pwritev2", true, 5, SSIZE_T,
    INT, CONST_STRUCT_IOVEC_P, INT, OFF_T, INT, 0},
{-1, "end", false, 0, 0, 0, 0, 0, 0, 0, 0}
};

#endif /* !LINUX_SYSTEM_CALL_H_ */
